# MMLU-Pro Enriched Dataset (Full View)

Explore `data/mmlu_pro_full_enriched.csv`: shape, null counts, and one sample row per model.

Generate the file with:

```bash
python scripts/download_mmlu_pro.py
python scripts/build_mmlu_pro_dataset.py
python scripts/enrich_mmlu_pro_full.py
```

In [1]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_PATH = PROJECT_ROOT / "data" / "mmlu_pro_full_enriched.csv"

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 120)

df = pd.read_csv(DATA_PATH)
df.head(3)

,question,llm_model,error,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,is_open_source,knowledge_cutoff_year,multilingual_support,temperature,top_p,top_k,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy,question_length_words,question_length_chars,question_complexity_score,has_few_shot_examples,prompt_contains_system_instructions,question_category,is_ambiguous,contains_negation,context_token_count
0,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",DeepSeek-Coder-V2,no_error,DeepSeek-Coder-V2,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.18,0.31,47,192,17.74,False,False,Engineering,False,False,58
1,Stack is also known as\n\nA. FIFO memory\nB. Flash memory\nC. LIFO memory\nD. LILO memory,DeepSeek-Coder-V2,no_error,DeepSeek-Coder-V2,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.18,0.31,17,84,5.50,False,False,Engineering,False,False,21
2,The errors mainly caused by human mistakes are\n\nA. gross error.\nB. instrumental error.\nC. systematic error.,DeepSeek-Coder-V2,no_error,DeepSeek-Coder-V2,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.18,0.31,17,107,11.86,False,False,Engineering,False,False,21

## Overview

In [2]:
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")
print(f"Models: {df['llm_model'].nunique()}")
print()
print(list(df.columns))
print()
df.info()

Rows: 563,787
Columns: 35
Models: 47

['question', 'llm_model', 'error', 'model_name', 'context_window_tokens', 'max_output_tokens', 'vocab_size', 'positional_encoding_type', 'attention_type', 'tokenizer_type', 'is_open_source', 'knowledge_cutoff_year', 'multilingual_support', 'temperature', 'top_p', 'top_k', 'repetition_penalty', 'frequency_penalty', 'presence_penalty', 'max_tokens_requested', 'stop_sequences_count', 'galileo_qa_no_rag', 'galileo_qa_with_rag', 'galileo_longform', 'crag_hallucination_rate', 'crag_accuracy', 'question_length_words', 'question_length_chars', 'question_complexity_score', 'has_few_shot_examples', 'prompt_contains_system_instructions', 'question_category', 'is_ambiguous', 'contains_negation', 'context_token_count']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 563787 entries, 0 to 563786
Data columns (total 35 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   question                             563787 non-null  object
 1   llm_model                            563787 non-null  object
 2   error                                563787 non-null  object
 3   model_name                           563787 non-null  object
 4   context_window_tokens                563787 non-null  int64
 5   max_output_tokens                    563787 non-null  int64
 6   vocab_size                           563787 non-null  int64
 7   positional_encoding_type             563787 non-null  object
 8   attention_type                       563787 non-null  object
 9   tokenizer_type                       563787 non-null  object
 10  is_open_source                       563787 non-null  bool
 11  knowledge_cutoff_year                563787 non-null  int64
 12  multilingual_support                 563787 non-null  bool
 13  temperature                          563787 non-null  float64
 14  top_p                                563787 non-null  float64
 15  top_k                                383463 non-null  float64
 16  repetition_penalty                   383463 non-null  float64
 17  frequency_penalty                    180324 non-null  float64
 18  presence_penalty                     180324 non-null  float64
 19  max_tokens_requested                 563787 non-null  int64
 20  stop_sequences_count                 563787 non-null  int64
 21  galileo_qa_no_rag                    563787 non-null  float64
 22  galileo_qa_with_rag                  563787 non-null  float64
 23  galileo_longform                     563787 non-null  float64
 24  crag_hallucination_rate              563787 non-null  float64
 25  crag_accuracy                        563787 non-null  float64
 26  question_length_words                563787 non-null  int64
 27  question_length_chars                563787 non-null  int64
 28  question_complexity_score            563787 non-null  float64
 29  has_few_shot_examples                563787 non-null  bool
 30  prompt_contains_system_instructions  563787 non-null  bool
 31  question_category                    563787 non-null  object
 32  is_ambiguous                         563787 non-null  bool
 33  contains_negation                    563787 non-null  bool
 34  context_token_count                  563787 non-null  int64
dtypes: bool(6), float64(12), int64(9), object(8)
memory usage: 128.0+ MB

## Null counts

In [3]:
null_counts = df.isnull().sum()
null_pct = (null_counts / len(df) * 100).round(4)
null_summary = pd.DataFrame({"null_count": null_counts, "null_pct": null_pct})
null_summary = null_summary[null_summary["null_count"] > 0].sort_values("null_count", ascending=False)

if null_summary.empty:
    print("No null values in any column.")
else:
    display(null_summary)

print()
print(f"Total null cells: {int(df.isnull().sum().sum()):,}")

                    null_count  null_pct
frequency_penalty       383463   68.0156
presence_penalty        383463   68.0156
top_k                   180324   31.9844
repetition_penalty      180324   31.9844

Total null cells: 1,127,574

## Label distribution

In [4]:
print(df["error"].value_counts().to_string())
print()
print(df.groupby(["llm_model", "error"]).size().unstack(fill_value=0).to_string())

error
error       282844
no_error    280943

error                        error  no_error
llm_model
DeepSeek-Coder-V2             3765      6586
Llama-2-13b-hf                9202      2830
Llama-2-70b-hf                7666      4366
Llama-2-7b-hf                 9825      2207
Meta-Llama-3-70B              5774      6258
Meta-Llama-3-70B-Instruct     5413      6774
Meta-Llama-3-8B               7920      4112
Meta-Llama-3-8B-Instruct      7205      4827
Meta-Llama-3_1-70B            5719      6313
Meta-Llama-3_1-70B-Instruct   4473      7559
Meta-Llama-3_1-8B             7641      4391
Meta-Llama-3_1-8B-Instruct    6715      5317
Mistral-7B-Instruct-v0.1      9126      2906
Mistral-7B-Instruct-v0.2      8572      3460
Mistral-7B-v0.1               8450      3582
Mistral-7B-v0.2-hf            8522      3510
Mixtral-8x7B-Instruct-v0.1    6992      5040
Mixtral-8x7B-v0.1             7234      4798
Phi-3-mini-4k-instruct        7041      4991
Qwen1.5-110B                  6112      5920
Qwen1.5-14B-Chat              7674      4358
Qwen1.5-72B-Chat              6359      5673
Qwen1.5-7B-Chat               8851      3181
Yi-34B                        6969      5063
Yi-6B                         9028      3004
Yi-6b-Chat                    8807      3225
arx_0314                      2045      9960
arx_3                         2618      9413
c4ai-command-r-v01            7629      4403
claude-3-5-haiku-20241022     4558      7474
claude-3-5-sonnet-20241022    2690      9342
claude-3.5-sonnet             2873      9157
deepseek                      5701      6296
deepseek-chat-v2_5            4111      7921
flash_0shots_00_35_03         4918      7114
gemini-1.5-flash-002          4313      7699
gemini-1.5-pro-002            3576      8444
gemma-7b                      8139      3893
gpt-4o-2024-08-06             3047      8985
gpt-4o-mini                   4441      7591
gpt4o(2024-05-13)             3361      8671
iask_pro                      2246      9693
jamba-1.5-large               6081      5951
mathstral-7B                  6979      5053
opus_2shots_00_37_14          3795      8237
sonnet-3.5_0shots_09_34_29    3268      8764
sonnet_0shots_12_01_18        5400      6631

## One sample per model (all 47)

First row for each `llm_model`. Question text is truncated for display.

In [5]:
samples = df.groupby("llm_model", as_index=False).first().sort_values("llm_model")
assert len(samples) == df["llm_model"].nunique()

samples_display = samples.copy()
samples_display["question"] = samples_display["question"].str.replace("\n", " ", regex=False).str.slice(0, 120) + "..."
samples_display

,llm_model,question,error,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,is_open_source,knowledge_cutoff_year,multilingual_support,temperature,top_p,top_k,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy,question_length_words,question_length_chars,question_complexity_score,has_few_shot_examples,prompt_contains_system_instructions,question_category,is_ambiguous,contains_negation,context_token_count
0,DeepSeek-Coder-V2,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,DeepSeek-Coder-V2,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.18,0.31,47,192,17.74,False,False,Engineering,False,False,58
1,Llama-2-13b-hf,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Llama-2-13b-hf,4096,2048,32000,RoPE,MHA,sentencepiece_BPE,True,2023,False,0.6,0.90,50.0,1.10,NaN,NaN,2048,1,0.58,0.61,0.73,0.34,0.19,78,570,10.30,False,False,Business,False,True,97
2,Llama-2-70b-hf,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Llama-2-70b-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2023,False,0.6,0.90,50.0,1.10,NaN,NaN,2048,1,0.64,0.67,0.79,0.29,0.22,78,570,10.30,False,False,Business,False,True,97
3,Llama-2-7b-hf,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Llama-2-7b-hf,4096,2048,32000,RoPE,MHA,sentencepiece_BPE,True,2023,False,0.6,0.90,50.0,1.10,NaN,NaN,2048,1,0.52,0.55,0.67,0.39,0.16,78,570,10.30,False,False,Business,False,True,97
4,Meta-Llama-3-70B,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Meta-Llama-3-70B,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.71,0.73,0.83,0.24,0.27,78,570,10.30,False,False,Business,False,True,97
5,Meta-Llama-3-70B-Instruct,What was the significance of the Gulf of Tonkin resolution? A. It triggered a global protest against US involvement...,no_error,Meta-Llama-3-70B-Instruct,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.73,0.75,0.85,0.22,0.29,118,676,9.19,False,False,Other,False,False,147
6,Meta-Llama-3-8B,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Meta-Llama-3-8B,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.60,0.62,0.72,0.31,0.20,78,570,10.30,False,False,Business,False,True,97
7,Meta-Llama-3-8B-Instruct,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Meta-Llama-3-8B-Instruct,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.63,0.65,0.75,0.28,0.22,78,570,10.30,False,False,Business,False,True,97
8,Meta-Llama-3_1-70B,A person who received a Level 4 rating on the Rancho Los Amigos Scale of Cognitive Functioning: A. is unresponsive ...,error,Meta-Llama-3_1-70B,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.72,0.74,0.84,0.23,0.28,161,1006,12.57,False,False,Psychology,False,True,201
9,Meta-Llama-3_1-70B-Instruct,A person who received a Level 4 rating on the Rancho Los Amigos Scale of Cognitive Functioning: A. is unresponsive ...,error,Meta-Llama-3_1-70B-Instruct,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.75,0.77,0.87,0.20,0.31,161,1006,12.57,False,False,Psychology,False,True,201
10,Meta-Llama-3_1-8B,A person who received a Level 4 rating on the Rancho Los Amigos Scale of Cognitive Functioning: A. is unresponsive ...,error,Meta-Llama-3_1-8B,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.62,0.64,0.74,0.29,0.21,161,1006,12.57,False,False,Psychology,False,True,201
11,Meta-Llama-3_1-8B-Instruct,A person who received a Level 4 rating on the Rancho Los Amigos Scale of Cognitive Functioning: A. is unresponsive ...,no_error,Meta-Llama-3_1-8B-Instruct,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.65,0.67,0.77,0.26,0.24,161,1006,12.57,False,False,Psychology,False,True,201
12,Mistral-7B-Instruct-v0.1,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Mistral-7B-Instruct-v0.1,8192,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.60,0.63,0.70,0.30,0.21,78,570,10.30,False,False,Business,False,True,97
13,Mistral-7B-Instruct-v0.2,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Mistral-7B-Instruct-v0.2,32768,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.62,0.65,0.72,0.28,0.22,78,570,10.30,False,False,Business,False,True,97
14,Mistral-7B-v0.1,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Mistral-7B-v0.1,8192,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.57,0.60,0.67,0.33,0.19,78,570,10.30,False,False,Business,False,True,97
15,Mistral-7B-v0.2-hf,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Mistral-7B-v0.2-hf,32768,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.59,0.62,0.69,0.31,0.20,78,570,10.30,False,False,Business,False,True,97
16,Mixtral-8x7B-Instruct-v0.1,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Mixtral-8x7B-Instruct-v0.1,32768,4096,32000,RoPE,MoE,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.70,0.72,0.81,0.23,0.27,78,570,10.30,False,False,Business,False,True,97
17,Mixtral-8x7B-v0.1,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Mixtral-8x7B-v0.1,32768,4096,32000,RoPE,MoE,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.68,0.71,0.80,0.25,0.25,78,570,10.30,False,False,Business,False,True,97
18,Phi-3-mini-4k-instruct,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Phi-3-mini-4k-instruct,4096,4096,32064,RoPE,GQA,cl100k_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.61,0.63,0.76,0.30,0.21,78,570,10.30,False,False,Business,False,True,148
19,Qwen1.5-110B,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Qwen1.5-110B,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.22,0.30,78,570,10.30,False,False,Business,False,True,97
20,Qwen1.5-14B-Chat,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Qwen1.5-14B-Chat,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.67,0.69,0.77,0.27,0.24,78,570,10.30,False,False,Business,False,True,97
21,Qwen1.5-72B-Chat,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Qwen1.5-72B-Chat,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.72,0.74,0.82,0.24,0.28,78,570,10.30,False,False,Business,False,True,97
22,Qwen1.5-7B-Chat,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Qwen1.5-7B-Chat,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.62,0.64,0.72,0.30,0.21,78,570,10.30,False,False,Business,False,True,97
23,Yi-34B,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,Yi-34B,4096,4096,64000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,40.0,1.10,NaN,NaN,4096,0,0.69,0.72,0.80,0.26,0.25,78,570,10.30,False,False,Business,False,True,97
24,Yi-6B,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Yi-6B,4096,4096,64000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,40.0,1.10,NaN,NaN,4096,0,0.55,0.58,0.66,0.35,0.18,78,570,10.30,False,False,Business,False,True,97
25,Yi-6b-Chat,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",error,Yi-6b-Chat,4096,4096,64000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,40.0,1.10,NaN,NaN,4096,0,0.57,0.60,0.68,0.33,0.19,78,570,10.30,False,False,Business,False,True,97
26,arx_0314,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,arx_0314,131072,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.82,0.81,0.88,0.12,0.36,47,192,17.74,False,False,Engineering,False,False,87
27,arx_3,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,arx_3,131072,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.79,0.78,0.85,0.14,0.34,47,192,17.74,False,False,Engineering,False,False,87
28,c4ai-command-r-v01,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,c4ai-command-r-v01,131072,4096,256000,RoPE,GQA,bytelevel_BPE,True,2024,True,0.3,0.90,50.0,1.05,NaN,NaN,4096,0,0.66,0.69,0.79,0.27,0.24,78,570,10.30,False,False,Business,False,True,97
29,claude-3-5-haiku-20241022,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,claude-3-5-haiku-20241022,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.74,0.73,0.80,0.16,0.32,47,192,17.74,False,False,Engineering,False,False,87
30,claude-3-5-sonnet-20241022,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,claude-3-5-sonnet-20241022,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.81,0.80,0.87,0.13,0.35,47,192,17.74,False,False,Engineering,False,False,87
31,claude-3.5-sonnet,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,claude-3.5-sonnet,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.80,0.79,0.86,0.14,0.34,47,192,17.74,False,False,Engineering,False,False,87
32,deepseek,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",error,deepseek,65536,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.70,0.72,0.82,0.22,0.28,47,192,17.74,False,False,Engineering,False,False,58
33,deepseek-chat-v2_5,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,deepseek-chat-v2_5,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.76,0.78,0.85,0.17,0.32,47,192,17.74,False,False,Engineering,False,False,58
34,flash_0shots_00_35_03,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,flash_0shots_00_35_03,1048576,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.72,0.71,0.78,0.18,0.30,78,570,10.30,False,False,Business,False,True,148
35,gemini-1.5-flash-002,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,gemini-1.5-flash-002,1048576,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.73,0.72,0.79,0.17,0.31,47,192,17.74,False,False,Engineering,False,False,87
36,gemini-1.5-pro-002,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,gemini-1.5-pro-002,2097152,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.78,0.77,0.84,0.14,0.34,47,192,17.74,False,False,Engineering,False,False,87
37,gemma-7b,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,gemma-7b,8192,4096,256000,RoPE,MHA,sentencepiece_BPE,True,2024,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.58,0.60,0.74,0.32,0.20,78,570,10.30,False,False,Business,False,True,97
38,gpt-4o-2024-08-06,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,gpt-4o-2024-08-06,128000,16384,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,16384,0,0.79,0.78,0.85,0.13,0.34,47,192,17.74,False,False,Engineering,False,False,87
39,gpt-4o-mini,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,gpt-4o-mini,128000,16384,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,16384,0,0.71,0.70,0.77,0.19,0.29,47,192,17.74,False,False,Engineering,False,False,87
40,gpt4o(2024-05-13),"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,gpt4o(2024-05-13),128000,4096,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,4096,0,0.78,0.77,0.84,0.14,0.33,47,192,17.74,False,False,Engineering,False,False,87
41,iask_pro,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,iask_pro,131072,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.80,0.79,0.86,0.13,0.35,47,192,17.74,False,False,Engineering,False,False,87
42,jamba-1.5-large,"What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4...",no_error,jamba-1.5-large,262144,4096,65536,RoPE,hybrid_Mamba,bytelevel_BPE,True,2024,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.68,0.70,0.79,0.26,0.25,47,192,17.74,False,False,Engineering,False,False,58
43,mathstral-7B,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,mathstral-7B,32768,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.64,0.67,0.74,0.28,0.23,78,570,10.30,False,False,Business,False,True,97
44,opus_2shots_00_37_14,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,opus_2shots_00_37_14,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.83,0.82,0.89,0.11,0.37,78,570,10.30,False,False,Business,False,True,148
45,sonnet-3.5_0shots_09_34_29,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,sonnet-3.5_0shots_09_34_29,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.80,0.79,0.86,0.14,0.34,78,570,10.30,False,False,Business,False,True,148
46,sonnet_0shots_12_01_18,"Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unneces...",no_error,sonnet_0shots_12_01_18,200000,4096,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,4096,0,0.76,0.75,0.82,0.16,0.31,78,570,10.30,False,False,Business,False,True,148

## Full row detail per model

All columns for each model (question truncated).

In [6]:
feature_cols = [c for c in df.columns if c not in ("question",)]

for _, row in samples.sort_values("llm_model").iterrows():
    print("=" * 100)
    print(f"llm_model: {row['llm_model']}")
    print(f"error: {row['error']}")
    print("question:")
    print(row["question"][:500] + ("..." if len(row["question"]) > 500 else ""))
    print()
    print(row[feature_cols].to_string())
    print()

====================================================================================================
llm_model: DeepSeek-Coder-V2
error: no_error
question:
What will be the number of lamps, each having 300 lumens, required to obtain an average illuminance of 50 lux on a 4m * 3m rectangular room?

A. 6
B. 1
C. 2
D. 5
E. 7
F. 3
G. 9
H. 10
I. 8
J. 4

llm_model                              DeepSeek-Coder-V2
error                                           no_error
model_name                             DeepSeek-Coder-V2
context_window_tokens                             131072
max_output_tokens                                   8192
vocab_size                                        102400
positional_encoding_type                            RoPE
attention_type                                       MoE
tokenizer_type                             bytelevel_BPE
is_open_source                                      True
knowledge_cutoff_year                               2024
multilingual_support                                True
temperature                                          0.6
top_p                                               0.95
top_k                                               50.0
repetition_penalty                                  1.05
frequency_penalty                                    NaN
presence_penalty                                     NaN
max_tokens_requested                                8192
stop_sequences_count                                   0
galileo_qa_no_rag                                   0.74
galileo_qa_with_rag                                 0.76
galileo_longform                                    0.84
crag_hallucination_rate                             0.18
crag_accuracy                                       0.31
question_length_words                                 47
question_length_chars                                192
question_complexity_score                          17.74
has_few_shot_examples                              False
prompt_contains_system_instructions                False
question_category                            Engineering
is_ambiguous                                       False
contains_negation                                  False
context_token_count                                   58

====================================================================================================
llm_model: Llama-2-13b-hf
error: no_error
question:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practi...

llm_model                                 Llama-2-13b-hf
error                                           no_error
model_name                                Llama-2-13b-hf
context_window_tokens                               4096
max_output_tokens                                   2048
vocab_size                                         32000
positional_encoding_type                            RoPE
attention_type                                       MHA
tokenizer_type                         sentencepiece_BPE
is_open_source                                      True
knowledge_cutoff_year                               2023
multilingual_support                               False
temperature                                          0.6
top_p                                                0.9
top_k                                               50.0
repetition_penalty                                   1.1
frequency_penalty                                    NaN
presence_penalty                                     NaN
max_tokens_requested                                2048
stop_sequences_count                                   1
galileo_qa_no_rag                                   0.58
galileo_qa_with_rag                                 0.61
galileo_longform                                    0.73
crag_hallucination_rate                             0.34
crag_accuracy                                       0.19
question_length_words                                 78
question_length_chars                                570
question_complexity_score                           10.3
has_few_shot_examples                              False
prompt_contains_system_instructions                False
question_category                               Business
is_ambiguous                                       False
contains_negation                                   True
context_token_count                                   97

====================================================================================================
llm_model: Llama-2-70b-hf
error: error
question:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practi...

llm_model                                 Llama-2-70b-hf
error                                              error
model_name                                Llama-2-70b-hf
context_window_tokens                               4096
max_output_tokens                                   2048
vocab_size                                         32000
positional_encoding_type                            RoPE
attention_type                                       GQA
tokenizer_type                         sentencepiece_BPE
is_open_source                                      True
knowledge_cutoff_year                               2023
multilingual_support                               False
temperature                                          0.6
top_p                                                0.9
top_k                                               50.0
repetition_penalty                                   1.1
frequency_penalty                                    NaN
presence_penalty                                     NaN
max_tokens_requested                                2048
stop_sequences_count                                   1
galileo_qa_no_rag                                   0.64
galileo_qa_with_rag                                 0.67
galileo_longform                                    0.79
crag_hallucination_rate                             0.29
crag_accuracy                                       0.22
question_length_words                                 78
question_length_chars                                570
question_complexity_score                           10.3
has_few_shot_examples                              False
prompt_contains_system_instructions                False
question_category                               Business
is_ambiguous                                       False
contains_negation                                   True
context_token_count                                   97

====================================================================================================
llm_model: Llama-2-7b-hf
error: error
question:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practi...

llm_model                                  Llama-2-7b-hf
error                                              error
model_name                                 Llama-2-7b-hf
context_window_tokens                               4096
max_output_tokens                                   2048
vocab_size                                         32000
positional_encoding_type                            RoPE
attention_type                                       MHA
tokenizer_type                         sentencepiece_BPE
is_open_source                                      True
knowledge_cutoff_year                               2023
multilingual_support                               False
temperature                                          0.6
top_p                                                0.9
top_k                                               50.0
repetition_penalty                                   1.1
frequency_penalty                                    NaN
presence_penalty                                     NaN
max_tokens_requested                                2048
stop_sequences_count                                   1
galileo_qa_no_rag                                   0.52
galileo_qa_with_rag                                 0.55
galileo_longform                                    0.67
crag_hallucination_rate                             0.39
crag_accuracy                                       0.16
question_length_words                                 78
question_length_chars                                570
question_complexity_score                           10.3
has_few_shot_examples                              False
prompt_contains_system_instructions                False
question_category                               Business
is_ambiguous                                       False
contains_negation                                   True
context_token_count                                   97

====================================================================================================
llm_model: Meta-Llama-3-70B
error: no_error
question:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practi...

llm_model                               Meta-Llama-3-70B
error                                           no_error
model_name                              Meta-Llama-3-70B
context_window_tokens                               8192
max_output_tokens                                   4096
vocab_size                                        128256
positional_encoding_type                            RoPE
attention_type                                       GQA
tokenizer_type                         sentencepiece_BPE
is_open_source                                      True
knowledge_cutoff_year                               2023
multilingual_support                                True
temperature                                          0.6
top_p                                                0.9
top_k                                               50.0
repetition_penalty                                   1.1
frequency_penalty                                    NaN
presence_penalty                                     NaN
max_tokens_requested                                4096
stop_sequences_count                                   1
galileo_qa_no_rag                                   0.71
galileo_qa_with_rag                                 0.73
galileo_longform                                    0.83
crag_hallucination_rate                             0.24
crag_accuracy                                       0.27
question_length_words                                 78
question_length_chars                                570
question_complexity_score                           10.3
has_few_shot_examples                              False
prompt_contains_system_instructions                False
question_category                               Business
is_ambiguous                                       False
contains_negation                                   True
context_token_count                                   97

====================================================================================================
llm_model: Meta-Llama-3-70B-Instruct
error: no_error
question:
What was the significance of the Gulf of Tonkin resolution?

A. It triggered a global protest against US involvement in Vietnam
B. It resulted in a significant reduction of US troops in Vietnam
C. It allowed the US to intensify its involvement in Vietnam
D. It illustrated the influence of public opinion on US foreign policy
E. It marked the beginning of diplomatic negotiations with Vietnam
F. It enhanced Congressional control over the Vietnam War
G. It curtailed US involvement in Vietnam
H. It e...

llm_model                              Meta-Llama-3-70B-Instruct
error                                                   no_error
model_name                             Meta-Llama-3-70B-Instruct
context_window_tokens                                       8192
max_output_tokens                                           4096
vocab_size                                                128256
positional_encoding_type                                    RoPE
attention_type                                               GQA
tokenizer_type                                 sentencepiece_BPE
is_open_source                                              True
knowledge_cutoff_year                                       2023
multilingual_support                                        True
temperature                                                  0.6
top_p                                                        0.9
top_k                                                       50.0
repetition_penalty                                           1.1
frequency_penalty                                            NaN
presence_penalty                                             NaN
max_tokens_requested                                        4096
stop_sequences_count                                           1
galileo_qa_no_rag                                           0.73
galileo_qa_with_rag                                         0.75
galileo_longform                                            0.85
crag_hallucination_rate                                     0.22
crag_accuracy                                               0.29
question_length_words                                        118
question_length_chars                                        676
question_complexity_score                                   9.19
has_few_shot_examples                                      False
prompt_contains_system_instructions                        False
question_category                                          Other
is_ambiguous                                               False
contains_negation                                          False
context_token_count                                          147

====================================================================================================
llm_model: Meta-Llama-3-8B
error: no_error
question:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practi...

llm_model                                Meta-Llama-3-8B
error                                           no_error
model_name                               Meta-Llama-3-8B
context_window_tokens                               8192
max_output_tokens                                   4096
vocab_size                                        128256
positional_encoding_type                            RoPE
attention_type                                       GQA
tokenizer_type                         sentencepiece_BPE
is_open_source                                      True
knowledge_cutoff_year                               2023
multilingual_support                                True
temperature                                          0.6
top_p                                                0.9
top_k                                               50.0
repetition_penalty                                   1.1
frequency_penalty                                    NaN
presence_penalty                                     NaN
max_tokens_requested                                4096
stop_sequences_count                                   1
galileo_qa_no_rag                                    0.6
galileo_qa_with_rag                                 0.62
galileo_longform                                    0.72
crag_hallucination_rate                             0.31
crag_accuracy                                        0.2
question_length_words                                 78
question_length_chars                                570
question_complexity_score                           10.3
has_few_shot_examples                              False
prompt_contains_system_instructions                False
question_category                               Business
is_ambiguous                                       False
contains_negation                                   True
context_token_count                                   97

====================================================================================================
llm_model: Meta-Llama-3-8B-Instruct
error: no_error
question:
Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practi...

llm_model                              Meta-Llama-3-8B-Instruct
error                                                  no_error
model_name                             Meta-Llama-3-8B-Instruct
context_window_tokens                                      8192
max_output_tokens                                          4096
vocab_size                                               128256
positional_encoding_type                                   RoPE
attention_type                                              GQA
tokenizer_type                                sentencepiece_BPE
is_open_source                                             True
knowledge_cutoff_year                                      2023
multilingual_support                                       True
temperature                                                 0.6
top_p                                                       0.9
top_k                                                      50.0
repetition_penalty                                          1.1
frequency_penalty                                           NaN
presence_penalty                                            NaN

## Model-level features (unique per model)

In [7]:
model_feature_cols = [
    "model_name",
    "context_window_tokens",
    "max_output_tokens",
    "vocab_size",
    "positional_encoding_type",
    "attention_type",
    "tokenizer_type",
    "is_open_source",
    "knowledge_cutoff_year",
    "multilingual_support",
    "temperature",
    "top_p",
    "top_k",
    "repetition_penalty",
    "frequency_penalty",
    "presence_penalty",
    "max_tokens_requested",
    "stop_sequences_count",
    "galileo_qa_no_rag",
    "galileo_qa_with_rag",
    "galileo_longform",
    "crag_hallucination_rate",
    "crag_accuracy",
]

df.groupby("llm_model")[model_feature_cols].first().sort_index()

,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,is_open_source,knowledge_cutoff_year,multilingual_support,temperature,top_p,top_k,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy
llm_model,,,,,,,,,,,,,,,,,,,,,,,
DeepSeek-Coder-V2,DeepSeek-Coder-V2,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.18,0.31
Llama-2-13b-hf,Llama-2-13b-hf,4096,2048,32000,RoPE,MHA,sentencepiece_BPE,True,2023,False,0.6,0.90,50.0,1.10,NaN,NaN,2048,1,0.58,0.61,0.73,0.34,0.19
Llama-2-70b-hf,Llama-2-70b-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2023,False,0.6,0.90,50.0,1.10,NaN,NaN,2048,1,0.64,0.67,0.79,0.29,0.22
Llama-2-7b-hf,Llama-2-7b-hf,4096,2048,32000,RoPE,MHA,sentencepiece_BPE,True,2023,False,0.6,0.90,50.0,1.10,NaN,NaN,2048,1,0.52,0.55,0.67,0.39,0.16
Meta-Llama-3-70B,Meta-Llama-3-70B,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.71,0.73,0.83,0.24,0.27
Meta-Llama-3-70B-Instruct,Meta-Llama-3-70B-Instruct,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.73,0.75,0.85,0.22,0.29
Meta-Llama-3-8B,Meta-Llama-3-8B,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.60,0.62,0.72,0.31,0.20
Meta-Llama-3-8B-Instruct,Meta-Llama-3-8B-Instruct,8192,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.63,0.65,0.75,0.28,0.22
Meta-Llama-3_1-70B,Meta-Llama-3_1-70B,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.72,0.74,0.84,0.23,0.28
Meta-Llama-3_1-70B-Instruct,Meta-Llama-3_1-70B-Instruct,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.75,0.77,0.87,0.20,0.31
Meta-Llama-3_1-8B,Meta-Llama-3_1-8B,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.62,0.64,0.74,0.29,0.21
Meta-Llama-3_1-8B-Instruct,Meta-Llama-3_1-8B-Instruct,131072,4096,128256,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,50.0,1.10,NaN,NaN,4096,1,0.65,0.67,0.77,0.26,0.24
Mistral-7B-Instruct-v0.1,Mistral-7B-Instruct-v0.1,8192,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.60,0.63,0.70,0.30,0.21
Mistral-7B-Instruct-v0.2,Mistral-7B-Instruct-v0.2,32768,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.62,0.65,0.72,0.28,0.22
Mistral-7B-v0.1,Mistral-7B-v0.1,8192,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.57,0.60,0.67,0.33,0.19
Mistral-7B-v0.2-hf,Mistral-7B-v0.2-hf,32768,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.59,0.62,0.69,0.31,0.20
Mixtral-8x7B-Instruct-v0.1,Mixtral-8x7B-Instruct-v0.1,32768,4096,32000,RoPE,MoE,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.70,0.72,0.81,0.23,0.27
Mixtral-8x7B-v0.1,Mixtral-8x7B-v0.1,32768,4096,32000,RoPE,MoE,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.68,0.71,0.80,0.25,0.25
Phi-3-mini-4k-instruct,Phi-3-mini-4k-instruct,4096,4096,32064,RoPE,GQA,cl100k_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.61,0.63,0.76,0.30,0.21
Qwen1.5-110B,Qwen1.5-110B,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.74,0.76,0.84,0.22,0.30
Qwen1.5-14B-Chat,Qwen1.5-14B-Chat,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.67,0.69,0.77,0.27,0.24
Qwen1.5-72B-Chat,Qwen1.5-72B-Chat,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.72,0.74,0.82,0.24,0.28
Qwen1.5-7B-Chat,Qwen1.5-7B-Chat,32768,8192,151936,RoPE,GQA,bytelevel_BPE,True,2024,True,0.7,0.80,20.0,1.05,NaN,NaN,8192,0,0.62,0.64,0.72,0.30,0.21
Yi-34B,Yi-34B,4096,4096,64000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,40.0,1.10,NaN,NaN,4096,0,0.69,0.72,0.80,0.26,0.25
Yi-6B,Yi-6B,4096,4096,64000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,40.0,1.10,NaN,NaN,4096,0,0.55,0.58,0.66,0.35,0.18
Yi-6b-Chat,Yi-6b-Chat,4096,4096,64000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.6,0.90,40.0,1.10,NaN,NaN,4096,0,0.57,0.60,0.68,0.33,0.19
arx_0314,arx_0314,131072,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.82,0.81,0.88,0.12,0.36
arx_3,arx_3,131072,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.79,0.78,0.85,0.14,0.34
c4ai-command-r-v01,c4ai-command-r-v01,131072,4096,256000,RoPE,GQA,bytelevel_BPE,True,2024,True,0.3,0.90,50.0,1.05,NaN,NaN,4096,0,0.66,0.69,0.79,0.27,0.24
claude-3-5-haiku-20241022,claude-3-5-haiku-20241022,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.74,0.73,0.80,0.16,0.32
claude-3-5-sonnet-20241022,claude-3-5-sonnet-20241022,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.81,0.80,0.87,0.13,0.35
claude-3.5-sonnet,claude-3.5-sonnet,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.80,0.79,0.86,0.14,0.34
deepseek,deepseek,65536,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.70,0.72,0.82,0.22,0.28
deepseek-chat-v2_5,deepseek-chat-v2_5,131072,8192,102400,RoPE,MoE,bytelevel_BPE,True,2024,True,0.6,0.95,50.0,1.05,NaN,NaN,8192,0,0.76,0.78,0.85,0.17,0.32
flash_0shots_00_35_03,flash_0shots_00_35_03,1048576,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.72,0.71,0.78,0.18,0.30
gemini-1.5-flash-002,gemini-1.5-flash-002,1048576,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.73,0.72,0.79,0.17,0.31
gemini-1.5-pro-002,gemini-1.5-pro-002,2097152,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.78,0.77,0.84,0.14,0.34
gemma-7b,gemma-7b,8192,4096,256000,RoPE,MHA,sentencepiece_BPE,True,2024,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.58,0.60,0.74,0.32,0.20
gpt-4o-2024-08-06,gpt-4o-2024-08-06,128000,16384,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,16384,0,0.79,0.78,0.85,0.13,0.34
gpt-4o-mini,gpt-4o-mini,128000,16384,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,16384,0,0.71,0.70,0.77,0.19,0.29
gpt4o(2024-05-13),gpt4o(2024-05-13),128000,4096,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,4096,0,0.78,0.77,0.84,0.14,0.33
iask_pro,iask_pro,131072,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.80,0.79,0.86,0.13,0.35
jamba-1.5-large,jamba-1.5-large,262144,4096,65536,RoPE,hybrid_Mamba,bytelevel_BPE,True,2024,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.68,0.70,0.79,0.26,0.25
mathstral-7B,mathstral-7B,32768,4096,32000,RoPE,GQA,sentencepiece_BPE,True,2023,True,0.7,0.90,50.0,1.05,NaN,NaN,4096,0,0.64,0.67,0.74,0.28,0.23
opus_2shots_00_37_14,opus_2shots_00_37_14,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.83,0.82,0.89,0.11,0.37
sonnet-3.5_0shots_09_34_29,sonnet-3.5_0shots_09_34_29,200000,8192,100277,learned_absolute,MHA,cl100k_BPE,False,2024,True,1.0,1.00,NaN,NaN,0.0,0.0,8192,0,0.80,0.79,0.86,0.14,0.34
sonnet_0shots_12_01_18,sonnet_0shots_12_01_18,200000,4096,100277,learned_absolute,MHA,cl100k_BPE,False,2023,True,1.0,1.00,NaN,NaN,0.0,0.0,4096,0,0.76,0.75,0.82,0.16,0.31