# RealMistake Enriched Dataset (Full View)

All columns in `data/realmistake_full_enriched.csv`: original labels, model features, and question-based features.

Generate the file with:

```bash
python scripts/enrich_realmistake_full.py
python scripts/enrich_question_features.py
```

In [8]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_PATH = PROJECT_ROOT / "data" / "realmistake_full_enriched.csv"

df = pd.read_csv(DATA_PATH)
df.head(3)

,question,llm_model,error,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,is_open_source,knowledge_cutoff_year,multilingual_support,temperature,top_p,top_k,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy,question_length_words,question_length_chars,question_complexity_score,has_few_shot_examples,prompt_contains_system_instructions,question_category,is_ambiguous,contains_negation,context_token_count
0,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,274,1758,10.51,False,False,Reasoning,False,True,342
1,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,264,1690,10.27,False,False,Reasoning,False,True,330
2,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,no_error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,103,652,10.50,False,False,Reasoning,False,True,128

## Overview

In [9]:
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")
print()
print(list(df.columns))
print()
df.info()

Rows: 900
Columns: 35

['question', 'llm_model', 'error', 'model_name', 'context_window_tokens', 'max_output_tokens', 'vocab_size', 'positional_encoding_type', 'attention_type', 'tokenizer_type', 'is_open_source', 'knowledge_cutoff_year', 'multilingual_support', 'temperature', 'top_p', 'top_k', 'repetition_penalty', 'frequency_penalty', 'presence_penalty', 'max_tokens_requested', 'stop_sequences_count', 'galileo_qa_no_rag', 'galileo_qa_with_rag', 'galileo_longform', 'crag_hallucination_rate', 'crag_accuracy', 'question_length_words', 'question_length_chars', 'question_complexity_score', 'has_few_shot_examples', 'prompt_contains_system_instructions', 'question_category', 'is_ambiguous', 'contains_negation', 'context_token_count']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   question                             900 non-null    object
 1   llm_model                            900 non-null    object
 2   error                                900 non-null    object
 3   model_name                           900 non-null    object
 4   context_window_tokens                900 non-null    int64
 5   max_output_tokens                    900 non-null    int64
 6   vocab_size                           900 non-null    int64
 7   positional_encoding_type             900 non-null    object
 8   attention_type                       900 non-null    object
 9   tokenizer_type                       900 non-null    object
 10  is_open_source                       900 non-null    bool
 11  knowledge_cutoff_year                900 non-null    int64
 12  multilingual_support                 900 non-null    bool
 13  temperature                          900 non-null    float64
 14  top_p                                900 non-null    float64
 15  top_k                                480 non-null    float64
 16  repetition_penalty                   480 non-null    float64
 17  frequency_penalty                    420 non-null    float64
 18  presence_penalty                     420 non-null    float64
 19  max_tokens_requested                 900 non-null    int64
 20  stop_sequences_count                 900 non-null    int64
 21  galileo_qa_no_rag                    900 non-null    float64
 22  galileo_qa_with_rag                  900 non-null    float64
 23  galileo_longform                     900 non-null    float64
 24  crag_hallucination_rate              900 non-null    float64
 25  crag_accuracy                        900 non-null    float64
 26  question_length_words                900 non-null    int64
 27  question_length_chars                900 non-null    int64
 28  question_complexity_score            900 non-null    float64
 29  has_few_shot_examples                900 non-null    bool
 30  prompt_contains_system_instructions  900 non-null    bool
 31  question_category                    900 non-null    object
 32  is_ambiguous                         900 non-null    bool
 33  contains_negation                    900 non-null    bool
 34  context_token_count                  900 non-null    int64
dtypes: bool(6), float64(12), int64(9), object(8)
memory usage: 209.3+ KB

## Question-based feature summary

In [10]:
question_cols = [
    "question_length_words",
    "question_length_chars",
    "question_complexity_score",
    "has_few_shot_examples",
    "prompt_contains_system_instructions",
    "question_category",
    "is_ambiguous",
    "contains_negation",
    "context_token_count",
]
df[question_cols].describe(include="all").T

                                     count unique        top freq         mean          std    min    25%     50%     75%     max
question_length_words                900.0    NaN        NaN  NaN       292.93   173.403631  103.0  119.0   271.0   509.0   599.0
question_length_chars                900.0    NaN        NaN  NaN  1778.416667  1005.218825  645.0  744.0  1726.0  2986.0  3869.0
question_complexity_score            900.0    NaN        NaN  NaN    10.435633     1.167219   5.59   9.91   10.25   10.71   18.03
has_few_shot_examples                  900      1      False  900          NaN          NaN    NaN    NaN     NaN     NaN     NaN
prompt_contains_system_instructions    900      1      False  900          NaN          NaN    NaN    NaN     NaN     NaN     NaN
question_category                      900      4  Reasoning  585          NaN          NaN    NaN    NaN     NaN     NaN     NaN
is_ambiguous                           900      1      False  900          NaN          NaN    NaN    NaN     NaN     NaN     NaN
contains_negation                      900      1       True  900          NaN          NaN    NaN    NaN     NaN     NaN     NaN
context_token_count                  900.0    NaN        NaN  NaN   371.882222   229.034928  119.0  148.0   335.0  645.25  1108.0

In [11]:
pd.crosstab(df["question_category"], df["error"], margins=True)

error              error  no_error  All
question_category
Coding                16         8   24
Creative              37        13   50
Fact Retrieval       175        66  241
Reasoning            421       164  585
All                  649       251  900

## Model feature profiles

In [12]:
model_cols = [c for c in df.columns if c not in ("question", "error") and c not in question_cols]
df.groupby("llm_model", as_index=False)[model_cols].first().T

                                         0                               1
llm_model                       gpt-4-0613  meta-llama/Llama-2-70b-chat-hf
model_name                      gpt-4-0613             llama-2-70b-chat-hf
context_window_tokens                 8192                            4096
max_output_tokens                     4096                            2048
vocab_size                          100277                           32000
positional_encoding_type  learned_absolute                            RoPE
attention_type                         MHA                             GQA
tokenizer_type                  cl100k_BPE               sentencepiece_BPE
is_open_source                       False                            True
knowledge_cutoff_year                 2021                            2022
multilingual_support                  True                           False
temperature                            1.0                             0.6
top_p                                  1.0                             0.9
top_k                                  NaN                            50.0
repetition_penalty                     NaN                             1.2
frequency_penalty                      0.0                             NaN
presence_penalty                       0.0                             NaN
max_tokens_requested                  4096                            1024
stop_sequences_count                     0                               1
galileo_qa_no_rag                     0.77                            0.65
galileo_qa_with_rag                   0.76                            0.68
galileo_longform                      0.83                            0.82
crag_hallucination_rate              0.135                           0.287
crag_accuracy                        0.335                           0.223

## Full dataset (all columns)

Questions are truncated for display.

In [13]:
display_df = df.copy()
display_df["question"] = display_df["question"].str.slice(0, 100) + "..."

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 320)
pd.set_option("display.max_colwidth", 35)

display_df

                               question                       llm_model     error           model_name  context_window_tokens  max_output_tokens  vocab_size positional_encoding_type attention_type     tokenizer_type  is_open_source  knowledge_cutoff_year  multilingual_support  temperature  top_p  top_k  \
0    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
1    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
2    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
3    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
4    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
5    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
6    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
7    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
8    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
9    Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
10   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
11   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
12   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
13   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
14   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
15   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
16   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
17   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
18   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
19   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
20   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
21   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
22   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
23   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
24   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
25   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
26   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
27   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
28   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
29   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
30   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
31   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
32   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
33   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
34   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
35   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
36   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
37   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
38   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
39   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
40   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
41   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
42   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
43   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
44   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
45   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
46   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
47   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
48   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
49   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
50   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
51   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
52   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
53   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
54   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
55   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
56   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
57   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
58   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
59   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
60   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
61   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
62   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0
63   Generate a math word problem th...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6    0.9   50.0

## Sample rows with all columns (untruncated question preview)

In [14]:
sample = df.head(5).copy()
sample["question"] = sample["question"].str.slice(0, 200) + "..."
sample

,question,llm_model,error,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,is_open_source,knowledge_cutoff_year,multilingual_support,temperature,top_p,top_k,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy,question_length_words,question_length_chars,question_complexity_score,has_few_shot_examples,prompt_contains_system_instructions,question_category,is_ambiguous,contains_negation,context_token_count
0,Generate a math word problem th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,274,1758,10.51,False,False,Reasoning,False,True,342
1,Generate a math word problem th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,264,1690,10.27,False,False,Reasoning,False,True,330
2,Generate a math word problem th...,meta-llama/Llama-2-70b-chat-hf,no_error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,103,652,10.50,False,False,Reasoning,False,True,128
3,Generate a math word problem th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,302,1914,10.52,False,False,Reasoning,False,True,377
4,Generate a math word problem th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223,115,703,10.71,False,False,Reasoning,False,True,143