# RealMistake Enriched Dataset

Full view of `data/realmistake_full_enriched.csv` with model architecture, inference defaults, and benchmark scores joined by `llm_model`.

Generate the file with:

```bash
python scripts/enrich_realmistake_full.py
```

In [1]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_PATH = PROJECT_ROOT / "data" / "realmistake_full_enriched.csv"

df = pd.read_csv(DATA_PATH)
df.head()

,question,llm_model,error,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,...,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy
0,Generate a math word problem that satisfies th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,...,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
1,Generate a math word problem that satisfies th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,...,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
2,Generate a math word problem that satisfies th...,meta-llama/Llama-2-70b-chat-hf,no_error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,...,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
3,Generate a math word problem that satisfies th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,...,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
4,Generate a math word problem that satisfies th...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,...,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223

## Overview

In [2]:
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")
print()
print(list(df.columns))
print()
df.info()

Rows: 900
Columns: 26

['question', 'llm_model', 'error', 'model_name', 'context_window_tokens', 'max_output_tokens', 'vocab_size', 'positional_encoding_type', 'attention_type', 'tokenizer_type', 'is_open_source', 'knowledge_cutoff_year', 'multilingual_support', 'temperature', 'top_p', 'top_k', 'repetition_penalty', 'frequency_penalty', 'presence_penalty', 'max_tokens_requested', 'stop_sequences_count', 'galileo_qa_no_rag', 'galileo_qa_with_rag', 'galileo_longform', 'crag_hallucination_rate', 'crag_accuracy']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   question                  900 non-null    object
 1   llm_model                 900 non-null    object
 2   error                     900 non-null    object
 3   model_name                900 non-null    object
 4   context_window_tokens     900 non-null    int64
 5   max_output_tokens         900 non-null    int64
 6   vocab_size                900 non-null    int64
 7   positional_encoding_type  900 non-null    object
 8   attention_type            900 non-null    object
 9   tokenizer_type            900 non-null    object
 10  is_open_source            900 non-null    bool
 11  knowledge_cutoff_year     900 non-null    int64
 12  multilingual_support      900 non-null    bool
 13  temperature               900 non-null    float64
 14  top_p                     900 non-null    float64
 15  top_k                     480 non-null    float64
 16  repetition_penalty        480 non-null    float64
 17  frequency_penalty         420 non-null    float64
 18  presence_penalty          420 non-null    float64
 19  max_tokens_requested      900 non-null    int64
 20  stop_sequences_count      900 non-null    int64
 21  galileo_qa_no_rag         900 non-null    float64
 22  galileo_qa_with_rag       900 non-null    float64
 23  galileo_longform          900 non-null    float64
 24  crag_hallucination_rate   900 non-null    float64
 25  crag_accuracy             900 non-null    float64
dtypes: bool(2), float64(11), int64(6), object(7)
memory usage: 170.6+ KB

## Model feature profiles (one row per model)

In [3]:
feature_cols = [c for c in df.columns if c not in ("question", "llm_model", "error")]
model_profiles = df.groupby("llm_model", as_index=False)[feature_cols].first()
model_profiles.T

                                         0                               1
llm_model                       gpt-4-0613  meta-llama/Llama-2-70b-chat-hf
model_name                      gpt-4-0613             llama-2-70b-chat-hf
context_window_tokens                 8192                            4096
max_output_tokens                     4096                            2048
vocab_size                          100277                           32000
positional_encoding_type  learned_absolute                            RoPE
attention_type                         MHA                             GQA
tokenizer_type                  cl100k_BPE               sentencepiece_BPE
is_open_source                       False                            True
knowledge_cutoff_year                 2021                            2022
multilingual_support                  True                           False
temperature                            1.0                             0.6
top_p                                  1.0                             0.9
top_k                                  NaN                            50.0
repetition_penalty                     NaN                             1.2
frequency_penalty                      0.0                             NaN
presence_penalty                       0.0                             NaN
max_tokens_requested                  4096                            1024
stop_sequences_count                     0                               1
galileo_qa_no_rag                     0.77                            0.65
galileo_qa_with_rag                   0.76                            0.68
galileo_longform                      0.83                            0.82
crag_hallucination_rate              0.135                           0.287
crag_accuracy                        0.335                           0.223

## Label balance by model

In [4]:
pd.crosstab(df["llm_model"], df["error"], margins=True)

error                           error  no_error  All
llm_model
gpt-4-0613                        262       158  420
meta-llama/Llama-2-70b-chat-hf    387        93  480
All                               649       251  900

## Full dataset (all columns)

Questions are truncated for display; all feature columns are shown in full.

In [5]:
display_df = df.copy()
display_df["question"] = display_df["question"].str.slice(0, 120) + "..."

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 300)
pd.set_option("display.max_colwidth", 40)

display_df

                                    question                       llm_model     error           model_name  context_window_tokens  max_output_tokens  vocab_size positional_encoding_type attention_type     tokenizer_type  is_open_source  knowledge_cutoff_year  multilingual_support  temperature  \
0    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
1    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
2    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
3    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
4    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
5    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
6    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
7    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
8    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
9    Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
10   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
11   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
12   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
13   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
14   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
15   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
16   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
17   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
18   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
19   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
20   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
21   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
22   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
23   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
24   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
25   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
26   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
27   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
28   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
29   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
30   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
31   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
32   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
33   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
34   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
35   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
36   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
37   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
38   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
39   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
40   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
41   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
42   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
43   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
44   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
45   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
46   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
47   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
48   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
49   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
50   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
51   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
52   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
53   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf  no_error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
54   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
55   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
56   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
57   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
58   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
59   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
60   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
61   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
62   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
63   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
64   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6
65   Generate a math word problem that sa...  meta-llama/Llama-2-70b-chat-hf     error  llama-2-70b-chat-hf                   4096               2048       32000                     RoPE            GQA  sentencepiece_BPE            True                   2022                 False          0.6

## Export-friendly sample (first 10 rows, all columns)

In [6]:
df.head(10)

,question,llm_model,error,model_name,context_window_tokens,max_output_tokens,vocab_size,positional_encoding_type,attention_type,tokenizer_type,is_open_source,knowledge_cutoff_year,multilingual_support,temperature,top_p,top_k,repetition_penalty,frequency_penalty,presence_penalty,max_tokens_requested,stop_sequences_count,galileo_qa_no_rag,galileo_qa_with_rag,galileo_longform,crag_hallucination_rate,crag_accuracy
0,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
1,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
2,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,no_error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
3,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
4,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
5,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
6,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
7,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
8,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223
9,Generate a math word problem that sa...,meta-llama/Llama-2-70b-chat-hf,error,llama-2-70b-chat-hf,4096,2048,32000,RoPE,GQA,sentencepiece_BPE,True,2022,False,0.6,0.9,50.0,1.2,NaN,NaN,1024,1,0.65,0.68,0.82,0.287,0.223

## Numeric feature summary

In [7]:
numeric_cols = df.select_dtypes(include="number").columns.tolist()
df.groupby("llm_model")[numeric_cols].first().T

llm_model                gpt-4-0613  meta-llama/Llama-2-70b-chat-hf
context_window_tokens      8192.000                        4096.000
max_output_tokens          4096.000                        2048.000
vocab_size               100277.000                       32000.000
knowledge_cutoff_year      2021.000                        2022.000
temperature                   1.000                           0.600
top_p                         1.000                           0.900
top_k                           NaN                          50.000
repetition_penalty              NaN                           1.200
frequency_penalty             0.000                             NaN
presence_penalty              0.000                             NaN
max_tokens_requested       4096.000                        1024.000
stop_sequences_count          0.000                           1.000
galileo_qa_no_rag             0.770                           0.650
galileo_qa_with_rag           0.760                           0.680
galileo_longform              0.830                           0.820
crag_hallucination_rate       0.135                           0.287
crag_accuracy                 0.335                           0.223